### ISSUE TITLE
Airplay not working

### ISSUE THREAD

**Issue by sozomai** [balenalabs/balena-sound#501]
The airplay server doesn't seem to be working. At least it is not showing up on any of my apple devices. In the logs it simply keeps saying " airplay  Waiting for audioblock to start..."

I also can't get the audio line in to work. I have a generic usb soundcard with both and audio in and out. When I plug in the soundcard the audio out works, but I can't get the audio in to work. I did add the device variable "SOUND_ENABLE_SOUNDCARD_INPUT."

I have a Raspberry pi 4 that I am running it on.

**Comment by AliMickey** [comment]
@lachlancresswell Can confirm same issue, attached screenshot from inside container as example.
![image](https://user-images.githubusercontent.com/60691199/140256014-a9f05069-1abc-4957-95c4-fa6dc56144a5.png)

However, it did not make a difference, still gives the pa context error.

**Comment by tmigone** [comment]
Fixed in v3.6.11. For details see https://github.com/balenalabs/balena-sound/pull/508

**Comment by CanadianBaconPro** [comment]
I am still having this issue as of 3.10.0

Running the command returns my routers local IP rather than the docker gateway. 
``bash
/usr/src # ip route | awk '/default / { print $3 }'
192.168.1.1
```

I am using balena sound on a raspberry Pi 3B+ on Wifi. 

Attempting the listed fix now, attached below are my log files from the edge device. 
[balena-sound_kitchen-speakers-2024-07-06t14_39_40-06_00.txt](https://github.com/user-attachments/files/16117305/balena-sound_kitchen-speakers-2024-07-06t14_39_40-06_00.txt)
